### ISSUE TITLE
dropping something in the search area

### ISSUE THREAD

**Issue by MareoRaft** [abrobbins90/groceries#2]
@abrobbins90 

It seems that currently, when someone drags a box (say, from the menu field) and drops it into the search field, the following happens

	$('#search_results').on("drop", function(event){
		event.preventDefault();
		let id = event.originalEvent.dataTransfer.getData("text")
		let node = graph.getNodeById(id)
		node.sendToLimbo()
		searchArea.launchSearch()
	})

in particular, the end result is

		searchArea.launchSearch()

I am confused that `node` is not an input to `searchArea.launchSearch`.

1. Does it currently just rerun the entire search?

2. Does the current search functionality purposefully omit any nodes that are already present in the menu?

-Matt

**Comment by abrobbins90** [comment]
yes and yes
